#!/usr/bin/env bash
# @author Jesus Alcaraz <jesus@gammapartners.com>
#

# check to see if I used a message, then it will behave as a put 
#bash shell script check input argument

# if value is not set  -- add
if [[ -z "$1"  ]]
  then
    git add .;
    git status;	exit
fi


# if everything else -- I implied if value is set
./put "add $*";
