#!/bin/bash

# set working directory as the scripts location during the execution of script
# cd "$(dirname "$0")"   uncommentand it will look inside _/clis/bash_scripts instead of your project

pwd

php "vendor/bin/behat" "$@"
