#!/bin/bash
# @author Jesus Alcaraz <jesus@gammapartners.com>
#
#bash shell script check input argument
if [ -z "$1" ]
  then
  	echo " "
    echo "Missing 1st argument "
    echo " "
	echo "Sample Usage:    - expects one arguments "
	echo " "
	echo "    describe table "
	echo "    ";
	./showtables;
	exit
fi

# set working directory as the scripts location during the execution of script 
cd "$(dirname "$0")"

TABLE="$1";


THISOUTPUT="$(php 'mysql_connectors')"
THISCONNECTOR=""

while read -r line; do
    #echo "... $line ..."
    THISCONNECTOR=$line
done <<< "$THISOUTPUT"
#    echo "-- $THISCONNECTOR --"
#exit

THISOUTPUT="$(php 'mysql_table')"
THISSCHEMA=""

while read -r line; do
    #echo "... $line ..."
    THISSCHEMA=$line
done <<< "$THISOUTPUT"

THISSQL="SELECT column_name FROM information_schema.columns WHERE table_name='${TABLE}' AND table_schema='${THISSCHEMA}';";


# No coloring for this
# This is used in the testing of models by Trait/ModelBasicTester.php
# display what this does

echo "~"; 

mysql -A  $THISCONNECTOR -B -s -e "$THISSQL"

echo "~"; 


