#!/usr/bin/env php
<?php
# @author Jesus Alcaraz <jesus@gammpartners.com>
#
# Procedural Programming dump sql from Laravel DB
# 
#
include('load_env');

//TEST VALUES
// $DB_DATABASE= "het2";
// $DB_DATABASE_LOGGER= "het2_logger";
// $DB_USERNAME= "root";
// $DB_PASSWORD= "toor";

# Before Loading anything Check Arguments Passed
# Get argv 
if (!isset($argv) || !isset($argv[1])) {
	#get script name
	$me=array_pop(explode(DIRECTORY_SEPARATOR,__FILE__));

	echo "
	Sample Usage:    
	    php $me tablename
	    ";
	$said=shell_exec('mysql -u'.$DB_USERNAME.' -p'.$DB_PASSWORD.' '.$DB_DATABASE.' -e "show tables;"');
	echo "\n". $said. "\n";
	die(0);
}
$table = $argv[1];

//$sql = "describe $table;";
$sql="SELECT column_name FROM information_schema.columns WHERE table_name='$table';";

# construct command to execute
$command = 'mysql -u'.$DB_USERNAME.' -p'.$DB_PASSWORD.' '.$DB_DATABASE.' -e "'.$sql.'"';

# display what this does
echo "\033[36m \n ".$sql . "\n " . $command ."\n\n";

echo "\033[33m "; 
$said=shell_exec($command );
echo "\033[31m "; 
echo "\n". $said. "\n";




