#!/usr/bin/env bash

# @author Jesus Alcaraz <jesus@gammpartners.com>
#bash shell script check input argument
if [ -z "$1" ]
  then
  	echo " "
    echo "Missing 1st argument "
    echo " "
	echo "Sample Usage:    - expects one arguments "
	echo " "
	echo "    describe table "
	echo "    ";
	./showtables;
	exit
fi

# set working directory as the scripts location during the execution of script 
cd "$(dirname "$0")"

TABLE="$1";


THISOUTPUT="$(php 'mysql_connectors')"
THISCONNECTOR=""

while read -r line; do
    #echo "... $line ..."
    THISCONNECTOR=$line
done <<< "$THISOUTPUT"
#    echo "-- $THISCONNECTOR --"
#exit



THISSQL="SELECT column_name FROM information_schema.columns WHERE table_name='${TABLE}';";




red=`tput setaf 1`
cyan=`tput setaf 6`
green=`tput setaf 2`
reset=`tput sgr0`




#Colors reference
#Light Gray 0;37 
#Dark Gray 1;30
#Light Blue 1;34
#Light Green 1;32
#Light Cyan 1;36
#Light Red 1;31
#Light Purple 1;35
#Yellow 1;33
#White 1;37

# display what this does
echo "${cyan} mysql  ${THISCONNECTOR} -e '${THISSQL}'";

echo "${green}  "; 

mysql  $THISCONNECTOR -e "$THISSQL"


