#!/usr/bin/env php
<?php
# @author Jesus Alcaraz <jesus@gammpartners.com>
#
# Procedural Programming dump sql from Laravel DB
# 
#
include('load_env');
//TEST VALUES
// $DB_DATABASE= "het2";
// $DB_DATABASE_LOGGER= "het2_logger";
// $DB_USERNAME= "root";
// $DB_PASSWORD= "toor";

# Before Loading anything Check Arguments Passed
# Get argv 
$usage = 
"
	Sample Usage: 
	    php dump  target_file.sql
	    ";
$target_file = "het2.sql";

if ((isset($argv) || isset($argv[1])) && ($argv[1]=="-h"||$argv[1]=="/?"&&$argv[1]=="/h")) {
	echo $usage;
	die(0);
} 
if (isset($argv) || isset($argv[1])) {
	$target_file = $argv[1];

}

echo "\n".'mysqldump -u'.$DB_USERNAME.' -p'.$DB_PASSWORD.' '.$DB_DATABASE.' > '.$target_file ."\n\n";
$said=shell_exec('mysqldump -u'.$DB_USERNAME.' -p'.$DB_PASSWORD.' '.$DB_DATABASE.' > '.$target_file .' ');
echo "\n". $said. "\n";


