#!/usr/bin/env php
<?php
# @author Jesus Alcaraz <jesus@gammapartners.com>
#
# Procedural Programming place the sql in to the db
# 
#
include('load_env');
//TEST VALUES
// $DB_DATABASE= "het2";
// $DB_DATABASE_LOGGER= "het2_logger";
// $DB_USERNAME= "root";
// $DB_PASSWORD= "toor";

# Before Loading anything Check Arguments Passed
# Get argv 

$target_file = "het2.sql";

# Before Loading anything Check Arguments Passed
# Get argv 
if (!isset($argv) || !isset($argv[1])) {
	echo "
	Sample Usage:    - expects only one Dir not more
	    php dumpin tablename
	    ";
	  echo "";
	shell_exec('ls *.sql  | xargs -0 echo "dumpin');
	die(0);
}

if (isset($argv) || isset($argv[1])) {
	$target_file = $argv[1];

}

use Carbon\Carbon;

$starttime = Carbon::now();


echo "\n".'mysql -A -u'.$DB_USERNAME.' -p'.$DB_PASSWORD.' '.$DB_DATABASE.' < '.$target_file ."\n\n";
$said=shell_exec('mysql -A -u'.$DB_USERNAME.' -p'.$DB_PASSWORD.' '.$DB_DATABASE.' < '.$target_file .' ');
echo "\n". $said. "\n";

$endtime = Carbon::now();


say($colors, "Generated on ", $endtime->formatLocalized('%A %d %B %Y'));
say($colors, "Generated in ", $endtime->diffInMinutes($starttime) . ' minutes');
say($colors, "Generated in ", $endtime->diffInSeconds($starttime) . ' seconds');
$said=@exec(" paplay boy.ogg ");
