#!/bin/bash
# 
# Back to clone using file system, with su user
# @author Jesus Alcaraz <jesus@gammapartners.com>
#

sudo rm -rf /var/lib/mysql/het2_very
sudo cp -rf /var/lib/mysql/het2 /var/lib/mysql/het2_very
sudo chown -R mysql:mysql /var/lib/mysql/het2_very
sudo ls -la /var/lib/mysql
sudo ls -la /var/lib/mysql/het2_very


echo -e "\033[38;5;0;32m  \033[40m  GENERATED IN: \033[0m"
trap times EXIT
paplay boy.ogg 
