#!/usr/bin/env bash
# 
# Back to clone using file system, with su user
# @author Jesus Alcaraz <jesus@gammapartners.com>
#

sudo mkdir -p /var/lib/mysql/het2_big
sudo cp -rf /var/lib/mysql/het2/*.* /var/lib/mysql/het2_big
sudo cp -rf /var/lib/mysql/het2/* /var/lib/mysql/het2_big
sudo cp -rf /var/lib/mysql/het2/.* /var/lib/mysql/het2_big
sudo chown -R mysql:mysql /var/lib/mysql/het2_big
sudo ls -la /var/lib/mysql


echo -e "\033[38;5;0;32m  \033[40m  GENERATED IN: \033[0m"
trap times EXIT
paplay boy.ogg 
