#!/bin/bash
# @author Jesus Alcaraz <jesus@gammapartners.com>
#
#bash shell script check input argument
if [ -z "$1" ]
  then
    echo " "
    echo "Missing 1st argument "
    echo " "
  echo "Sample Usage:    - expects one argument "
  echo " "
  echo "    find seek-this "
  echo "    ";
  exit
fi

red=`tput setaf 1`
cyan=`tput setaf 6`
green=`tput setaf 2`
reset=`tput sgr0`

SEEKER="./ack";
IGNORE_COMMAND="ignore";

msg_red () {
    printf "\n${bdr}%s ${off}%s\n" "$@"
}

trap '{ msg_red " KEYBOARD INTERRUPT."; exit 130; }' INT

if command -v ag >/dev/null 2>&1; then
  {

    #msg_green " ag INSTALLED."
    SEEKER="ag";
  }
else 
  {

  #msg_red " NEED TO INSTALL ag."
    #msg_red " ENTER SUDO PASSOWRD AND PRESS ENTER."
  #sudo apt-get install silversearcher-ag -fy 
  
  if command -v ack >/dev/null 2>&1; then
    {

      #msg_green " ack INSTALLED."
    SEEKER="ack";
    }
  else 
    {

    #msg_red " NEED TO INSTALL ack."
      #msg_red " ENTER SUDO PASSOWRD AND PRESS ENTER."
    #sudo apt-get install ack-grep -fy 

    ls ./ack  | egrep 'ack' &>/dev/null
    if [ $? == 0 ]; then
      {

        #msg_green " ack INSTALLED."
      SEEKER="./ack";
      }
    else 
      {

      #msg_red " NEED TO INSTALL ./ack "
        #msg_red " ENTER SUDO PASSOWRD AND PRESS ENTER."
      # cp ~/bin/ack . 

      if command -v grep >/dev/null 2>&1; then
        {

          #msg_green " grep INSTALLED."
          SEEKER="grep";
          IGNORE_COMMAND="exclude";
        }
      else 
        {

        echo "${green} ${red} CANNOT SEARCH ....MISSING SEARCHER ACK OR  AG OR ./ACK NOR  GREP  ";
        exit 1;
          #msg_red " NEED TO INSTALL grep."
        } 
   
      fi
      }
    fi
    }
  fi
  }
fi


SEEKING="$1";


#echo $0=./replace



echo "   ";
echo "${reset} ${green} Seek ignoring vendor, bower_components, node_modules, storage/debugbar, app/Stub and storage/logs with ${SEEKER} -- "

echo "${reset} ${green} Finding ${reset} $SEEKING ${green}  with  ${SEEKER} ." 
echo "   ";
# echo "${cyan}  ack  --ignore-dir=vendor --ignore-dir=bower_components  --ignore-dir=node_modules --ignore-dir=storage/debugbar  --ignore-dir=storage/logs  --ignore-dir=app/Stubs \"${SEEKING}\" "
# echo "${cyan}  ag  --ignore-dir=vendor --ignore-dir=bower_components  --ignore-dir=node_modules --ignore-dir=storage/debugbar  --ignore-dir=storage/logs  --ignore-dir=app/Stubs \"${SEEKING}\" "
# echo "${cyan}  grep  --exclude-dir=vendor --exclude-dir=bower_components  --exclude-dir=node_modules --exclude-dir=storage/debugbar  --exclude-dir=storage/logs  --exclude-dir=app/Stubs \"${SEEKING}\" "
echo "   ";
# ack  --ignore-dir=vendor --ignore-dir=bower_components  --ignore-dir=node_modules --ignore-dir=storage/debugbar  --ignore-dir=storage/logs  --ignore-dir=app/Stubs "$SEEKING"  
# ag  --ignore-dir=vendor --ignore-dir=bower_components  --ignore-dir=node_modules --ignore-dir=storage/debugbar  --ignore-dir=storage/logs  --ignore-dir=app/Stubs "$SEEKING"
# grep  --exclude-dir=vendor --exclude-dir=bower_components  --exclude-dir=node_modules --exclude-dir=storage/debugbar  --exclude-dir=storage/logs  --exclude-dir=app/Stubs "$SEEKING" 
if [[ $SEEKING == *"/"* ]]
then
echo "${cyan}   ${SEEKER}  --${IGNORE_COMMAND}-dir=vendor --${IGNORE_COMMAND}-dir=bower_components  --${IGNORE_COMMAND}-dir=node_modules --${IGNORE_COMMAND}-dir=storage/debugbar  --${IGNORE_COMMAND}-dir=storage/logs  --${IGNORE_COMMAND}-dir=app/Stubs \"${SEEKING}\""
                ${SEEKER}  --${IGNORE_COMMAND}-dir=vendor --${IGNORE_COMMAND}-dir=bower_components  --${IGNORE_COMMAND}-dir=node_modules --${IGNORE_COMMAND}-dir=storage/debugbar  --${IGNORE_COMMAND}-dir=storage/logs  --${IGNORE_COMMAND}-dir=app/Stubs "$SEEKING"
else
echo "${cyan}   ${SEEKER}  --${IGNORE_COMMAND}-dir=vendor --${IGNORE_COMMAND}-dir=bower_components  --${IGNORE_COMMAND}-dir=node_modules --${IGNORE_COMMAND}-dir=storage/debugbar  --${IGNORE_COMMAND}-dir=storage/logs  --${IGNORE_COMMAND}-dir=app/Stubs \"${SEEKING}\" "
                ${SEEKER}  --${IGNORE_COMMAND}-dir=vendor --${IGNORE_COMMAND}-dir=bower_components  --${IGNORE_COMMAND}-dir=node_modules --${IGNORE_COMMAND}-dir=storage/debugbar  --${IGNORE_COMMAND}-dir=storage/logs  --${IGNORE_COMMAND}-dir=app/Stubs "$SEEKING" 
fi

