#!/usr/bin/env bash
# @author Jesus Alcaraz <jesus@gammapartners.com>
#
#bash shell script check input argument
if [ -z "$1" ]
  then
  	echo " "
    echo "Missing 1st argument "
    echo " "
	echo "Sample Usage:    - expects one argument "
	echo " "
	echo "    find seek-this "
	echo "    ";
	exit
fi


SEEKING="$1";

#echo $0=./replace


red=`tput setaf 1`
cyan=`tput setaf 6`
green=`tput setaf 2`
reset=`tput sgr0`

echo "   ";
# echo "${reset} ${green} Seek ignoring vendor, bower_components, node_modules, storage/debugbar, app/Stub and storage/logs with ack  "
echo "${reset} ${green} Seek ignoring vendor, bower_components, node_modules, storage/debugbar, app/Stub and storage/logs with ag --Silver Searcher- "
# echo "${reset} ${green} Finding ${reset} $SEEKING ${green}  with Ack." 
echo "${reset} ${green} Finding ${reset} $SEEKING ${green}  with Ag." 
echo "   ";
echo "${cyan}  ag  --ignore-dir=vendor --ignore-dir=bower_components  --ignore-dir=node_modules --ignore-dir=storage/debugbar  --ignore-dir=storage/logs  --ignore-dir=app/Stubs \"${SEEKING}\" "
# echo "${cyan}  ack  --ignore-dir=vendor --ignore-dir=bower_components  --ignore-dir=node_modules --ignore-dir=storage/debugbar  --ignore-dir=storage/logs  --ignore-dir=app/Stubs \"${SEEKING}\" "
echo "   ";
               ag  --ignore-dir=vendor --ignore-dir=bower_components  --ignore-dir=node_modules --ignore-dir=storage/debugbar  --ignore-dir=storage/logs --ignore-dir=app/Stubs "$SEEKING" 
               # ack  --ignore-dir=vendor --ignore-dir=bower_components  --ignore-dir=node_modules --ignore-dir=storage/debugbar  --ignore-dir=storage/logs --ignore-dir=app/Stubs "$SEEKING" 
