#!/bin/bash
# @author Jesus Alcaraz <jesus@gammapartners.com>
#

# check to see if I used a message, then it will behave as a put 
#bash shell script check input argument
if [ -z "$1" ]
  then
    git add .;
    git status;	exit
fi


./put "finish $*";
