#!/usr/bin/env bash

sudo chmod +x add 
sudo chmod +x artisan
sudo chmod +x autoload
sudo chmod +x branch
sudo chmod +x branches
sudo chmod +x branchUpdate.sh
sudo chmod +x checkout
sudo chmod +x commit 
sudo chmod +x controller
sudo chmod +x count 
sudo chmod +x dbmigrate
sudo chmod +x describe
sudo chmod +x dump
sudo chmod +x dumpin
sudo chmod +x dumpout
sudo chmod +x testenv
sudo chmod +x filelastestchanges
sudo chmod +x fileparticipation
sudo chmod +x fix_linux_permissions.sh
sudo chmod +x indatabase
sudo chmod +x forcepull
sudo chmod +x list
sudo chmod +x makeseeds
sudo chmod +x master
sudo chmod +x merge
sudo chmod +x migrate
sudo chmod +x model
sudo chmod +x newbranch
sudo chmod +x projectparticipation
sudo chmod +x pull
sudo chmod +x push
sudo chmod +x put
sudo chmod +x refresh
sudo chmod +x reset
sudo chmod +x routes
sudo chmod +x scite
sudo chmod +x seedTemplate
sudo chmod +x select
sudo chmod +x serve
sudo chmod +x showtables
sudo chmod +x squashdb
sudo chmod +x status
sudo chmod +x load_env
sudo chmod +x replace
sudo chmod +x tinker
sudo chmod +x updateme
