#!/usr/bin/env bash

sudo chmod +x add 
sudo chmod +x artisan
sudo chmod +x artisan.sh
sudo chmod +x autoload
sudo chmod +x branch
sudo chmod +x branches
sudo chmod +x branchUpdate.sh
sudo chmod +x checkout
sudo chmod +x commit 
sudo chmod +x controller
sudo chmod +x colorlist
sudo chmod +x count 
sudo chmod +x countlist 
sudo chmod +x countalltables 
sudo chmod +x dbmigrate
sudo chmod +x delete
sudo chmod +x describe
sudo chmod +x describelist
sudo chmod +x dump
sudo chmod +x dumpin
sudo chmod +x dumpout
sudo chmod +x duplicatetosmall
sudo chmod +x duplicatetovery
sudo chmod +x filecount
sudo chmod +x filelastestchanges
sudo chmod +x fileparticipation
sudo chmod +x fix_linux_permissions.sh
sudo chmod +x find
sudo chmod +x finish
sudo chmod +x findinfile
sudo chmod +x forcepull
sudo chmod +x frameworkload
sudo chmod +x frameworksave
sudo chmod +x generateinserts
sudo chmod +x generateparams
sudo chmod +x generatelocations
sudo chmod +x indatabase
sudo chmod +x last
sudo chmod +x list
sudo chmod +x load_env
sudo chmod +x load_all_sps
sudo chmod +x load_insert
sudo chmod +x locate
sudo chmod +x makeseeds
sudo chmod +x master
sudo chmod +x merge
sudo chmod +x migrate
sudo chmod +x model
sudo chmod +x mysql_connectors
sudo chmod +x mysql_connector
sudo chmod +x mysqlbackup
sudo chmod +x mysqlrestore
sudo chmod +x newbranch
sudo chmod +x projectparticipation
sudo chmod +x pull
sudo chmod +x push
sudo chmod +x put
sudo chmod +x phpunit
sudo chmod +x refresh
sudo chmod +x reset
sudo chmod +x routes
sudo chmod +x rollback
sudo chmod +x scite
sudo chmod +x seedTemplate
sudo chmod +x select
sudo chmod +x serve
sudo chmod +x seek
sudo chmod +x showtables
sudo chmod +x showtableslist
sudo chmod +x squashdb
sudo chmod +x status
sudo chmod +x replace
sudo chmod +x replaceinfile
sudo chmod +x restorefromvery
sudo chmod +x restorefromsmall
sudo chmod +x tinker
sudo chmod +x testenv
sudo chmod +x testexists
sudo chmod +x testerrorstoclipboard
sudo chmod +x testerrorstoclipboardcall
sudo chmod +x testdelete
sudo chmod +x testmodel
sudo chmod +x testmodelsall
sudo chmod +x testmigration
sudo chmod +x testview
sudo chmod +x testcontroller
sudo chmod +x testroute
sudo chmod +x testrequest
sudo chmod +x testsql
sudo chmod +x updateme
sudo chmod +x vendor/bin/phpunit
