#!/bin/bash
chmod +x ack
chmod +x add
chmod +x ag
chmod +x artisan.sh
chmod +x autoload
chmod +x branch
chmod +x branches
chmod +x branchUpdate.sh
chmod +x checkout
chmod +x colorlist
chmod +x Colors
chmod +x commit
chmod +x controller
chmod +x correct
chmod +x dbmigrate
chmod +x delete
chmod +x delete_broken_links
chmod +x describe
chmod +x describelist
chmod +x dumpout
chmod +x duplicatetobig
chmod +x duplicatetosmall
chmod +x duplicatetovery
chmod +x filecount
chmod +x filelastestchanges
chmod +x fileparticipation
chmod +x find
chmod +x find.bat
chmod +x findinfile
chmod +x finish
chmod +x fix
chmod +x fix_linux_permissions.sh
chmod +x fix_linux_permissions2.sh
chmod +x frameworkload
chmod +x frameworksave
chmod +x indatabase
chmod +x list
chmod +x load_all_sps
chmod +x locate
chmod +x makeseeds
chmod +x master
chmod +x merge
chmod +x migrate
chmod +x mysqlbackup
chmod +x mysqlrestore
chmod +x newbranch
chmod +x phpunit
chmod +x put
chmod +x refresh
chmod +x remove
chmod +x removed
chmod +x replace
chmod +x replaceinfile
chmod +x reset
chmod +x restorefrombig
chmod +x restorefromsmall
chmod +x restorefromvery
chmod +x rollback
chmod +x routes
chmod +x seek
chmod +x select
chmod +x serve
chmod +x showtables
chmod +x showtableslist
chmod +x status
chmod +x testerrorstoclipboard
chmod +x testerrorstoclipboardcall
chmod +x testsql
chmod +x tinker
chmod +x update

chmod +x vendor/bin/phpunit
