#!/bin/bash

sudo chmod +x ack
sudo chmod +x add
sudo chmod +x ag
sudo chmod +x artisan.sh
sudo chmod +x autoload
sudo chmod +x branch
sudo chmod +x branches
sudo chmod +x branchUpdate.sh
sudo chmod +x checkout
sudo chmod +x colorlist
sudo chmod +x Colors
sudo chmod +x commit
sudo chmod +x controller
sudo chmod +x correct
sudo chmod +x dbmigrate
sudo chmod +x delete
sudo chmod +x delete_broken_links
sudo chmod +x describe
sudo chmod +x describelist
sudo chmod +x dumpout
sudo chmod +x duplicatetobig
sudo chmod +x duplicatetosmall
sudo chmod +x duplicatetovery
sudo chmod +x filecount
sudo chmod +x filelastestchanges
sudo chmod +x fileparticipation
sudo chmod +x find
sudo chmod +x find.bat
sudo chmod +x findinfile
sudo chmod +x finish
sudo chmod +x fix
sudo chmod +x fix_linux_permissions.sh
sudo chmod +x fix_linux_permissions2.sh
sudo chmod +x frameworkload
sudo chmod +x frameworksave
sudo chmod +x indatabase
sudo chmod +x list
sudo chmod +x load_all_sps
sudo chmod +x locate
sudo chmod +x makeseeds
sudo chmod +x master
sudo chmod +x merge
sudo chmod +x migrate
sudo chmod +x mysqlbackup
sudo chmod +x mysqlrestore
sudo chmod +x newbranch
sudo chmod +x phpunit
sudo chmod +x put
sudo chmod +x refresh
sudo chmod +x remove
sudo chmod +x removed
sudo chmod +x replace
sudo chmod +x replaceinfile
sudo chmod +x reset
sudo chmod +x restorefrombig
sudo chmod +x restorefromsmall
sudo chmod +x restorefromvery
sudo chmod +x rollback
sudo chmod +x routes
sudo chmod +x seek
sudo chmod +x select
sudo chmod +x serve
sudo chmod +x showtables
sudo chmod +x showtableslist
sudo chmod +x status
sudo chmod +x testerrorstoclipboard
sudo chmod +x testerrorstoclipboardcall
sudo chmod +x testsql
sudo chmod +x tinker
sudo chmod +x update
sudo chmod +x vendor/bin/phpunit
