#!/bin/bash

chmod +x add 
chmod +x artisan
chmod +x artisan.sh
chmod +x autoload
chmod +x branch
chmod +x branches
chmod +x branchUpdate.sh
chmod +x checkout
chmod +x commit 
chmod +x controller
chmod +x colorlist
chmod +x count 
chmod +x countlist 
chmod +x countalltables 
chmod +x dbmigrate
chmod +x describe
chmod +x describelist
chmod +x dump
chmod +x dumpin
chmod +x dumpout
chmod +x duplicatetosmall
chmod +x duplicatetovery
chdmo +x filecount
chmod +x filelastestchanges
chmod +x fileparticipation
chmod +x fix_linux_permissions.sh
chmod +x find
chmod +x findinfile
chmod +x forcepull
chmod +x frameworkload
chmod +x frameworksave
chmod +x generateinserts
chmod +x generateparams
chmod +x generatelocations
chmod +x indatabase
chmod +x last
chmod +x list
chmod +x load_env
chmod +x load_all_sps
chmod +x load_insert
chmod +x locate
chmod +x makeseeds
chmod +x master
chmod +x merge
chmod +x migrate
chmod +x model
chmod +x mysql_connectors
chmod +x mysql_connector
chmod +x mysqlbackup
chmod +x mysqlrestore
chmod +x newbranch
chmod +x projectparticipation
chmod +x pull
chmod +x push
chmod +x put
chmod +x phpunit
chmod +x refresh
chmod +x reset
chmod +x routes
chmod +x rollback
chmod +x scite
chmod +x seedTemplate
chmod +x select
chmod +x serve
chmod +x seek
chmod +x showtables
chmod +x showtableslist
chmod +x squashdb
chmod +x status
chmod +x replace
chmod +x replaceinfile
chmod +x restorefromvery
chmod +x restorefromsmall
chmod +x tinker
chmod +x testenv
chmod +x testexists
chmod +x testerrorstoclipboard
chmod +x testerrorstoclipboardcall
chmod +x testdelete
chmod +x testmodel
chmod +x testmodelsall
chmod +x testmigration
chmod +x testview
chmod +x testcontroller
chmod +x testroute
chmod +x testrequest
chmod +x testsql
chmod +x updateme
chmod +x vendor/bin/phpunit
