#!/usr/bin/env php
<?php
# @author Jesus Alcaraz <jesus@gammpartners.com>
#

$currentbranch = exec('git rev-parse --abbrev-ref HEAD');
echo "Force Reseting Pull to  ".$currentbranch."\n" ;

//downloads the latest from remote without trying to merge or rebase anything.
$said = exec('git fetch --all');

//resets the master branch to what you just fetched. 
//The --hard option changes all the files in your working tree to match the files in origin/master
$said = exec('git reset --hard origin/'.$currentbranch);
echo $said . "\n";
echo "Project Participation: \n";
include('projectparticipation');