#!/usr/bin/env bash
echo "Recover .env"
cp ../.env .

echo "Recover composer.lock"
cp ../composer.lock .

echo "Recover composer.json"
cp ../composer.json .

echo "Recover bower_components"
cp -r ../bower_components .

echo "Recover vendor"
cp -r ../vendor .

echo "Recover node_modules"
cp -r ../node_modules .

echo "Recover directory for logs"
mkdir -p storage/logs

echo "Recover directory for debugbar"
mkdir -p storage/debugbar

echo "Finally Run composer-autoload"
composer dump-autoload
