#!/usr/bin/env bash

# @author Jesus Alcaraz <jesus@gammpartners.com>
THISOUTPUT="$(php 'mysql_connectors')"
THISCONNECTOR=""
echo "mysql ${THISCONNECTOR}"
while read -r line; do
    #echo "... $line ..."
    THISCONNECTOR=$line
done <<< "$THISOUTPUT"
    echo "-- $THISCONNECTOR --"
#exit
mysql $THISCONNECTOR
