#!/usr/bin/env bash

# @author Jesus Alcaraz <jesus@gammapartners.com>
#get script name
#$me="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"

# set working directory as the scripts location during the execution of script 
cd "$(dirname "$0")"


THISOUTPUT="$(php 'mysql_connectors')"
THISCONNECTOR=""
while read -r line; do
    #echo "... $line ..."
    THISCONNECTOR=$line
done <<< "$THISOUTPUT"
    # echo "-- $THISCONNECTOR --"
#exit
echo "find database/sp/  -name '*.sql' | awk '{ print \"source\",\$0 }' | mysql ${THISCONNECTOR}  --batch "
# mysql $THISCONNECTOR


# cd database/sp
find database/sp/ -name '*.sql' | awk '{ print "source",$0 }' | mysql -A $THISCONNECTOR --batch
# cd ..
# cd ..
