#!/usr/bin/env bash
# @author Jesus Alcaraz <jesus@gammapartners.com>
#
#bash shell script check input argument
if [ -z "$1" ]
  then
  	echo " "
    echo "Missing 1st argument "
    echo " "
	echo "Sample Usage:    - expects one argument "
	echo " "
	echo "    locate seek-this "
	echo "    ";
	exit
fi


SEEKING="$1";

#echo $0=./replace

echo "find a filename using find from linux "
echo "Locating $SEEKING " 
echo " "
find . | ag "/.*${SEEKING}[^/]*$" 
echo " "