#!/usr/bin/env php
<?php
# @author Jesus Alcaraz <jesus@gammpartners.com>
#

$pullcurrentbranch = exec('git rev-parse --abbrev-ref HEAD');
echo "Fetching git \n" ;
$said = exec('git fetch');
echo $said;
$said = exec('git pull origin '.$pullcurrentbranch);
echo "Pulling ".$pullcurrentbranch."\n" ;
echo $said . "\n";
