#!/usr/bin/env php
<?php
# @author Jesus Alcaraz <jesus@gammapartners.com>
#

$pullcurrentbranch = exec('git rev-parse --abbrev-ref HEAD');
echo "Fetching git \n" ;
$said = exec('git fetch');
echo $said;
$said = exec('git pull origin '.$pullcurrentbranch);
echo "Pulling ".$pullcurrentbranch."\n" ;
echo $said . "\n";

// $said = exec('composer dump-autoload');
// echo "Autoload \n" ;
// echo $said . "\n"; 

