#!/usr/bin/env php
<?php
# @author Jesus Alcaraz <jesus@gammapartners.com>
#

$currentbranch = exec('git rev-parse --abbrev-ref HEAD');
echo "Pushing ".$currentbranch."\n" ;
$said = exec('git push origin '.$currentbranch);
echo $said . "\n";
echo "Project Participation: \n";
include('projectparticipation');