#!/usr/bin/env bash
#
# @author Jesus Alcaraz <jesus@gammapartners.com>
#

# set working directory as the scripts location during the execution of script 
cd "$(dirname "$0")"


#add
echo
echo "=== Add . ===";
echo
git add .;

#status
echo
echo "=== Status ===";
echo
git status;
echo

#commit
OPTIONS="$@";
echo
echo "=== commit -am $OPTIONS ===";
echo
git commit -am "$OPTIONS";
echo

#pull
echo
echo "=== Pull ===";
echo
php "pull"  
echo

#push 
echo
echo "=== Push ===";
echo
php "push"
echo
