#!/bin/bash
#
# @author Jesus Alcaraz <jesus@gammapartners.com>
#

# set working directory as the scripts location during the execution of script 
cd "$(dirname "$0")"


#add
echo
echo -e "\\033[38;5;93m === Add . === \\033[38;5;123m ";
echo
git add .;

#status
echo
echo -e "\\033[38;5;93m === Status === \\033[38;5;123m";
echo
git status;
echo

#commit
OPTIONS="$@";
echo
echo -e "\\033[38;5;93m === commit -am $OPTIONS === \\033[38;5;123m";
echo
git commit -am "$OPTIONS";
echo

#pull
echo
echo -e "\\033[38;5;93m === Pull === \\033[38;5;123m";
echo
php "pull"  
echo

#push 
echo
echo -e "\\033[38;5;93m === Push === \\033[38;5;123m";
echo
php "push"
echo
