#!/bin/bash
# 
# Back to restore back into het2
# @author Jesus Alcaraz <jesus@gammapartners.com>
#

sudo cp -rf /var/lib/mysql/het2_big/*.* /var/lib/mysql/het2
sudo cp -rf /var/lib/mysql/het2_big/* /var/lib/mysql/het2
sudo cp -rf /var/lib/mysql/het2_big/.* /var/lib/mysql/het2
sudo chown -R mysql:mysql /var/lib/mysql/het2
sudo ls -la /var/lib/mysql


paplay boy.ogg 
echo -e "\033[38;5;0;32m  \033[40m  GENERATED IN: \033[0m"
trap times EXIT
