#!/usr/bin/env php
<?php
# @author Jesus Alcaraz <jesus@gammpartners.com>
#
# Procedural Programming place the sql in to the db
# 
#

include('load_env');
# Before Loading anything Check Arguments Passed
# Get argv 
if (!isset($argv) || !isset($argv[1])) {
	$me=exec(`basename "$0"`);
	echo "
	Sample Usage:    - expects only one Dir not more
	    php $me tablename
	    ";
	$said=shell_exec('mysql -u'.$DB_USERNAME.' -p'.$DB_PASSWORD.' '.$DB_DATABASE.' -e "show tables;"');
	echo "\n". $said. "\n";
	die(0);
}
$table = $argv[1];




$said=shell_exec('mysql -u'.$DB_USERNAME.' -p'.$DB_PASSWORD.' '.$DB_DATABASE.' -e "select * from  `'.$table.'`"');
echo "\n". $said. "\n";

   
