#!/usr/bin/env php
<?php
# @author Jesus Alcaraz <jesus@gammpartners.com>
#
# Procedural Programming to create 
# 
#

include('load_env');
# Before Loading anything Check Arguments Passed
# Get argv 

$said=shell_exec('mysql -u'.$DB_USERNAME.' -p'.$DB_PASSWORD.' -e "SHOW SCHEMAS;"');
	echo "\n". $said. "\n";
