#!/usr/bin/env php
<?php
# @author Jesus Alcaraz <jesus@gammapartners.com>
#
# Procedural Programming to Create 
# Models, Migrations, Controllers, and Tests, 
# 
#

//
//
//
// Step 1 Check Arguments
//
//
//

# Before Loading anything Check Arguments Passed
# Get argv 
if (!isset($argv) || !isset($argv[1])) {
	echo "
	Sample Usage:    - expects only one Dir not more
	    call testmodel Person\PersonAddress
	    call testmodel Person/PersonAddress
	    call testmodel PersonAddress
	    ";

	die(0);
}

include('generatebase');

#
#
#
#
# Creation Start
#
#
#
#



#
#
#
#
# Tests
#
#
#
#
// how to run a test exec('vendor/bin/phpunit tests/Models/'.$entity);

#
#
#
#
# Tests - controller
#
#
#
#

#base for tests generator
$base_folder = "tests/controllers";

$target_file = "basic_".$camelToUnderScoreFile."_controller_test.php";
$stub_file = "app/Stubs/Tests/controllers/controller_test.stub";

$file_targeted = generateFromStub($replace_array, $base_folder, $stub_file, $target_file, $dir, $file, $colors);






