#!/usr/bin/env php
<?php
# @author Jesus Alcaraz <jesus@gammapartners.com>
#
# Procedural Programming to Create 
# Migration Tests, 
# 
#

//
//
//
// Step 1 Check Arguments
//
//
//

# Before Loading anything Check Arguments Passed
# Get argv 
$valid_migration_types=[ "nothing", "run", "basic"];
$migration_type="basic";  /// simple|softdelete
if (!isset($argv) || !isset($argv[1])) {
	echo "
	Sample Usage:    - expects one or more arguments
	    call testmigration Person\PersonAddress [optional]
	    call testmigration Person/PersonAddress [optional]
	    call testmigration PersonAddress [optional]

	    [optional] can be:

	    " . implode("\n	    	- ", $valid_migration_types) ."

	    	- ".$migration_type." is default is ommited optional
";

	die(0);
}
if (isset($argv[2])) {
	if (in_array($migration_type, $valid_migration_types))	$migration_type = trim($argv[2]);
}
include('generatebase');

#
#
#
#
# Creation Start
#
#
#
#



#
#
#
#
# Tests
#
#
#
#
// how to run a test exec('vendor/bin/phpunit tests/Models/'.$entity);


#
#
#
#
# Tests - Migration
#
#
#
#


$base_folder = "tests/migration";
$target_file = $migration_type."_".$camelToUnderScoreFile."_migration_test.php";
$stub_file = "app/Stubs/Tests/migrations/".$migration_type."_migration_test.stub";;

$file_targeted = generateFromStub($replace_array, $base_folder, $stub_file, $target_file, $dir, $file, $colors, $type_of_creation=$migration_type." migration for ");

