#!/bin/bash

# @author Jesus Alcaraz <jesus@gammapartners.com>

# mysqladmin -uroot -ptoor  -i10 -r extended

# set working directory as the scripts location during the execution of script 
cd "$(dirname "$0")"


THISOUTPUT="$(php 'mysql_connector')"
THISCONNECTOR=""
while read -r line; do
    #echo "... $line ..."
    THISCONNECTOR=$line
done <<< "$THISOUTPUT"
    # echo "-- $THISCONNECTOR --"
#exit

mysqladmin $THISCONNECTOR  -i10 -r extended