#!/usr/bin/env php
<?php
# @author Jesus Alcaraz <jesus@gammapartners.com>
#
$updatemecurrentbranch = exec('git rev-parse --abbrev-ref HEAD');

# Before Loading anything Check Arguments Passed
# Get argv 

if (!isset($argv) || !isset($argv[1])  ) {
	$msg = 'Updating branch '.$updatemecurrentbranch.' with Master branch. Adding and commiting beforehand.';
} else {
	$argv[0] = "update ";
	$msg = implode(" ", $argv);
}

#add
echo "\n";
echo "\033[38;5;27m === Add .  ===\n \033[38;5;214m";
echo "\n";
$said = exec('git add . ');
echo $said ."\n";
echo "\n";

#commit
echo "\n";
echo "\033[38;5;27m === commit -am ".'"'. $msg . '"'. "   ===\n \033[38;5;214m";
echo "\n";
$said = exec('git commit -am "'.$msg .'"' );
echo $said ."\n";
echo "\n";


#pull
echo "\n";
echo "\033[38;5;27m === Pull  ===\n \033[38;5;214m";
echo "\n";
$said = exec('./pull');
echo $said ."\n";
echo "\n";

#push 
echo "\n";
echo "\033[38;5;27m === Push origin $updatemecurrentbranch  ===\n \033[38;5;214m";
echo "\n";
$said = exec('git push origin '.$updatemecurrentbranch);
echo $said ."\n";
echo "\n";

#master
echo "\n";
echo "\033[38;5;27m === Master  ===\n \033[38;5;214m";
echo "\n";
$said = exec('./master');
echo $said ."\n";
echo "\n";

#pull
echo "\n";
echo "\033[38;5;27m === Pull  ===\n \033[38;5;214m";
echo "\n";
$said = exec('./pull');
echo $said ."\n";
echo "\n";

#branch
echo "\n";
echo "\033[38;5;27m === Branch back $updatemecurrentbranch  ===\n \033[38;5;214m";
echo "\n";
$said = exec('./branch '.$updatemecurrentbranch);
echo $said ."\n";
echo "\n";

#merge
echo "\n";
echo "\033[38;5;27m === Merge Master Here  ===\n \033[38;5;214m";
echo "\n";
$said = exec('./merge master');
echo $said ."\n";